version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/chart-customs"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/experiment-manager"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/notebook-containerizer"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/notebook-search"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/vre-menu"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/vre-panel"
    schedule:
      interval: "monthly"


  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "


