version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/chart-customs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/experiment-manager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/notebook-containerizer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/notebook-search"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/vre-menu"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/vre-panel"
    schedule:
      interval: "daily"
      time: "16:35"
    open-pull-requests-limit: 1
    target-branch: "convert_secrets_to_variables"

  - package-ecosystem: "docker"
    directory: "/docker/vanilla"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "
