name: rclone-data-mounter
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab==3.5.0
  - nodejs==15.14.0
  - python==3.9.2
  - yarn
  - pip
  - pip:
      - pre-commit
      - ggshield
