name: jupyterlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - jupyterlab>=3.5.0
  - nodejs>=15.14.0
  - yarn>=1.22.19
  - pip>=22.3.1
  - pip:
    - setuptools_rust>=1.5.2
    - pyflakes>=2.4.0
    - colorhash>=1.0.4
    - requests>=2.26.0
    - tinydb>=4.6.1
    - PyGithub>=1.55
    - tornado>=6.1
    - notebook>=6.4.8
    - PyYAML>=6.0
    - nbformat>=5.7.0
    - autopep8>=1.6.0
    - Jinja2>=3.0.3
    - setuptools>=63.1.0
    - distro>=1.7.0