name: jupyterlab
channels:
  - conda-forge
dependencies:
  - jupyterhub
  - nbformat
  - widgetsnbextension
  - jupyterlab
  - nodejs=>18.13.0
  - python>=3.8
  - yarn=1.22.19
  - tinydb>=4.6.1
  - pygithub>=1.55
  - tornado>=6.1
  - notebook=6.5.2
  - pyyaml>=6.0
  - autopep8
  - Jinja2
  - distro
  - requests
  - colorhash
  - pyflakes
  - jupyter-videochat
  - jupyterlab-git
  - nbgitpuller
  - nb_conda_kernels>=2.3.1
  - rclone
  - jupyter-archive
  - zip
  - unzip
  - wget
  - git
  - jupyterlab-github
  - pathlib2
  - pip
  - r
  - r-irkernel
  - rpy2
  - r-renv
  - r-jsonlite
  - r-lobstr
  - r-rlang
  - r-purrr
  - r-optparse
  - jupyter-collaboration
  - pytest
  - flake8
  - r-optparse
#  - webdavclient3
#  - pandas
  - pip:
    - pytype~=2023.10.31
