name: jupyterlab
channels:
  - conda-forge
  - defaults
  - mathieu
dependencies:
  - python>=3.8
  - pip
  - tinydb>=4.6.1
  - pygithub>=1.55
  - tornado>=6.1
  - notebook
  - pyyaml>=6.0
  - nbformat
  - autopep8
  - Jinja2
  - distro
  - requests
  - colorhash
  - jupyterlab