name: jupyterlab
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.6.1
  - nodejs=18.13.0
  - python>=3.8
  - yarn==1.22.19
  - tinydb>=4.6.1
  - pygithub>=1.55
  - tornado>=6.1
  - notebook=6.5.2
  - pyyaml>=6.0
  - nbformat=5.7.3
  - autopep8=1.6.0
  - Jinja2=3.1.2
  - distro=1.8.0
  - requests=2.28.2
  - colorhash=1.0.4
  - pip==23.0.1
  - pyflakes=3.0.1
  - jupyter-videochat=0.6.0
  - jupyterlab-github=3.0.1
  - nbgitpuller=1.1.1
  - jupyterlab-lsp=3.10.2
  - python-lsp-server[all]
  - nb_conda_kernels=2.3.1
  - rclone=1.61.1
  - git
  - mamba
  - pip:
    - ggshield
    - pre-commit