name: jupyterlab
channels:
  - conda-forge
dependencies:
  - jupyterhub=4.0.2
  - nbformat=5.9.2
  - widgetsnbextension=4.0.10
  - jupyterlab=3.5.3
  - nodejs=20.9.0
  - python>=3.11
  - yarn=1.22.19
  - tinydb=4.8.0
  - pygithub=2.2.0
  - tornado=6.4
  - notebook=6.5.2
  - pyyaml=6.0.1
  - autopep8=2.0.4
  - Jinja2=3.1.3
  - distro=1.9.0
  - requests=2.31.0
  - colorhash=1.0.4
  - pyflakes=3.2.0
  - jupyter-videochat=0.6.0
  - jupyterlab-git=0.44.0
  - nbgitpuller=1.2.0
  - nb_conda_kernels=2.3.1
  - jupyter-archive=3.4.0
  - zip=3.0
  - unzip=6.0
  - wget=1.20.3
  - git=2.43.0
  - jupyterlab-github=3.0.1
  - pathlib2=2.3.7
  - pip=24.0
  - r=4.3
  - r-irkernel=1.3.2
  - rpy2=3.5.11
  - r-renv=1.0.5
  - r-jsonlite=1.8.8
  - r-lobstr=1.1.2
  - r-rlang=1.1.3
  - r-purrr=1.0.2
  - r-optparse=1.7.4
  - r-rcpp=1.0.12
  - r-rcppeigen=0.3.4.0.0
  - r-ggplot2=3.5.0
  - cmake=3.28.3
  - jupyter-collaboration=1.1.0
  - pytest=8.0.2
  - pytest-timeout=2.3.1
  - flake8=7.0.0
  - r-optparse=1.7.4
  - webdavclient3=3.14.5
  - pandas=2.2.1
  - zeromq=4.3.5
  - papermill=2.5.0
  - minio=7.2.5
  - rasterio=1.3.9
  - awesome-slugify=1.6.5
  - ipywidgets=8.1.2
  - pip:
    - pytype==2023.10.31