apiVersion: v1
kind: Service
metadata:
  name: naavre-visualizer-service
  namespace: argo
spec:
  selector:
    app: naavre-visualizer
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: naavre-visualizer-ingress
  namespace: argo
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: HOST
      http:
        paths:
          - path: /naavre-visualizer(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: naavre-visualizer-service
                port:
                  number: 5173