name: venv
channels:
  - conda-forge
  - defaults
  - enable_revoked
dependencies:
  - scipy
  - laspy
  - pip
  - ipywidgets
  - widgetsnbextension
  - rclone
  - wradlib
  - pip:
    - git+https://github.com/QCDIS/Laserfarm.git
