FROM jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e

USER root

#===== Add pdalpy dependencies ======
RUN apt-get update --allow-releaseinfo-change && apt-get -y install gcc g++
#====================================

ADD start-jupyter.sh /usr/local/bin/start-jupyter.sh
ADD jupyterlab_vre-0.1.0-py3-none-any.whl /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl
COPY ./notebooks/ /tmp/notebooks

RUN chmod ugo+x /usr/local/bin/start-jupyter.sh

USER $NB_USER

RUN conda remove --force -y terminado && \
    python -m pip install --upgrade pip

RUN python3 -m pip install --quiet --no-cache-dir /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl && \
    jupyter serverextension enable --py jupyterlab_vre --user


#===== Add pdalpy dependencies ======
RUN conda install --yes -c conda-forge pdal python-pdal gdal && \
    conda upgrade --yes numpy && \
    conda update --yes -n base conda && \
    pip install dask distributed lazperf==1.4.4 && \
    pip install laserfarm laspy
#====================================

COPY MULTIPLY_pip_requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /tmp
RUN git clone https://github.com/JorisTimmermans/atmospheric_correction.git
WORKDIR atmospheric_correction
RUN python setup.py develop


WORKDIR /tmp
RUN git clone https://github.com/JorisTimmermans/data-access.git
WORKDIR data-access
RUN python setup.py develop


WORKDIR /tmp
RUN git clone https://github.com/JorisTimmermans/multiply-core.git
WORKDIR multiply-core
RUN python setup.py develop

RUN ls
WORKDIR /tmp
RUN git clone https://github.com/QCDIS/inference-engine.git
WORKDIR inference-engine
RUN python setup.py develop

WORKDIR /tmp
RUN git clone https://github.com/QCDIS/prior-engine.git
WORKDIR prior-engine
RUN python setup.py develop

WORKDIR /tmp
RUN git clone https://github.com/JorisTimmermans/vm-support.git
WORKDIR vm-support
RUN python setup.py develop

WORKDIR /tmp
RUN git clone https://github.com/multiply-org/multiply-orchestration.git
WORKDIR multiply-orchestration
RUN python setup.py develop

WORKDIR /tmp
RUN git clone https://github.com/QCDIS/KaFKA-InferenceEngine.git
WORKDIR KaFKA-InferenceEngine
RUN python setup.py develop

WORKDIR /tmp
RUN git clone https://github.com/QCDIS/BRDF_descriptors.git
WORKDIR BRDF_descriptors
RUN python setup.py develop

WORKDIR $HOME

RUN pip install jupyterlab-github jupyter-videochat matplotlib folium cartopy icoscp pangaeapy && \
    jupyter serverextension enable --py jupyter_videochat --user && \
    jupyter serverextension enable --py jupyterlab_github --user


RUN pip uninstall pangaeapy -y
RUN pip uninstall requests -y
RUN pip install requests==2.27.0

RUN jupyter lab build --debug;

CMD ["/usr/local/bin/start-jupyter.sh"]