FROM qcdis/miniconda3-naavre AS naavre-build

RUN conda install -c conda-forge conda-pack
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar

RUN /venv/bin/conda-unpack


FROM qcdis/miniconda3-pdal AS naavre-build-pdal

RUN conda install -c conda-forge conda-pack

COPY --from=naavre-build /venv /venv-naavre
ENV PATH=/venv-naavre/bin:$PATH
ENV PATH=/home/jovyan/.local/bin:$PATH
RUN ["/bin/bash", "-c", "source /venv-naavre/bin/activate"]
RUN echo "source /venv-naavre/bin/activate" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

COPY laserfarm-environment.yaml .
ADD jupyterlab_vre-0.1.0-py3-none-any.whl /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl
RUN conda env update -f laserfarm-environment.yaml

RUN conda install -c conda-forge conda-pack
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv-naavre-pdal && cd /venv-naavre-pdal && tar xf /tmp/env.tar && \
    rm /tmp/env.tar

RUN /venv-naavre-pdal/bin/conda-unpack


FROM jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e AS runtime
USER root

COPY --from=naavre-build-pdal-build /venv-naavre-pdal /venv
ENV PATH=/venv/bin:$PATH
ENV PATH=/home/jovyan/.local/bin:$PATH
RUN source /venv/bin/activate
RUN echo "source /venv/bin/activate" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

ADD start-jupyter.sh /usr/local/bin/start-jupyter.sh
COPY ./repo_utils/ /tmp/repo_utils

RUN chmod ugo+x /usr/local/bin/start-jupyter.sh
RUN chown $NB_USER -R /venv/

USER $NB_USER
RUN jupyter serverextension enable --py jupyterlab_vre --user
RUN jupyter serverextension enable --py jupyter_videochat --user
RUN jupyter serverextension enable --py jupyterlab_github --user

RUN jupyter lab build --debug;
RUN conda clean -a -y
CMD ["/usr/local/bin/start-jupyter.sh"]