FROM jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e

USER root

#===== Add pdalpy dependencies ======
RUN apt-get update --allow-releaseinfo-change && apt-get -y install gcc g++
#====================================
RUN apt autoclean -y && apt autoremove -y

ADD start-jupyter.sh /usr/local/bin/start-jupyter.sh
ADD jupyterlab_vre-0.1.0-py3-none-any.whl /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl
COPY ./notebooks/ /tmp/notebooks

RUN chmod ugo+x /usr/local/bin/start-jupyter.sh

USER $NB_USER

RUN conda remove --force -y terminado && \
    python -m pip install --upgrade pip

RUN python3 -m pip install --quiet --no-cache-dir /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl && \
    jupyter serverextension enable --py jupyterlab_vre --user


#===== Add pdalpy dependencies ======
RUN conda install --yes -c conda-forge pdal python-pdal gdal && \
    conda upgrade --yes numpy && \
    conda update --yes -n base conda && \
    pip install dask distributed lazperf==1.4.4 && \
    pip install laserfarm laspy opencv-python-headless torch torchvision flwr sklearn tensorflow
#====================================

RUN pip install jupyterlab-github jupyter-videochat && \
    jupyter serverextension enable --py jupyter_videochat --user && \
    jupyter serverextension enable --py jupyterlab_github --user

RUN pip install matplotlib folium cartopy icoscp pangaeapy

RUN jupyter lab build --debug;

RUN conda clean -a -y
CMD ["/usr/local/bin/start-jupyter.sh"]