FROM continuumio/miniconda3 AS build
RUN conda install -c conda-forge conda-pack
COPY laserfarm-environment.yaml .
RUN conda update -n base -c conda-forge conda
ADD jupyterlab_vre-0.1.0-py3-none-any.whl /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl
RUN conda env update -f laserfarm-environment.yaml
RUN conda clean -a -y

RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar

RUN /venv/bin/conda-unpack


FROM jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e AS runtime
USER root

COPY --from=build /venv /venv
ENV PATH=/venv/bin:$PATH
ENV PATH=/home/jovyan/.local/bin:$PATH
RUN source /venv/bin/activate
RUN echo "source /venv/bin/activate" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

ADD start-jupyter.sh /usr/local/bin/start-jupyter.sh
COPY ./repo_utils/ /tmp/repo_utils

RUN chmod ugo+x /usr/local/bin/start-jupyter.sh
RUN chown $NB_USER -R /venv/

USER $NB_USER
RUN jupyter serverextension enable --py jupyterlab_vre --user
RUN jupyter serverextension enable --py jupyter_videochat --user
RUN jupyter serverextension enable --py jupyterlab_github --user

RUN jupyter lab build --debug;
RUN conda clean -a -y
CMD ["/usr/local/bin/start-jupyter.sh"]