FROM jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e

USER root

#===== Add MULTIPLY dependencies ======
RUN apt-get update --allow-releaseinfo-change && apt-get -y git unzip
RUN git clone https://github.com/JorisTimmermans/Deploy_MULTIPLY.git
#====================================
