FROM jupyterhub/k8s-singleuser-sample:1.1.3-n248.h20c9028e

USER root

RUN apt-get update --allow-releaseinfo-change && apt-get -y install git unzip

#========= Install_environments =======
RUN git clone https://github.com/JorisTimmermans/Deploy_MULTIPLY.git
WORKDIR Deploy_MULTIPLY
COPY MULTIPLY_requirements.txt .
RUN conda install --file MULTIPLY_requirements.txt

#====================================

#===== Add MULTIPLY dependencies ======

#====================================
