name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/multiply_core-0.6.1.dev0-py3-none-any.whl
    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/multiply_data_access-0.5.2-py3-none-any.whl
    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/multiply_inference_engine-0.6.1.dev0-py3-none-any.whl
#     - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/multiply_sar_pre_processing-0.1-py3-none-any.whl
#    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/BRDF_descriptors-1.3-py3-none-any.whl
#    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/KaFKA-0.0.0-py3-none-any.whl
##    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/SIAC-2.2.0-py2.py3-none-any.whl
#    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/SIAC-2.2.0-py3-none-any.whl
#    - https://github.com/QCDIS/Deploy_MULTIPLY/releases/download/0.1/vm_support-0.2.2-py3-none-any.whl