name: venv
channels:
  - conda-forge
  - defaults
  - enable_revoked
dependencies:
  - autopep8
  - colorhash
  - distro
  - git
  - Jinja2
  - jupyterhub
  - jupyterlab
  - jupyterlab-github
  - jupyterlab-lsp
  - jupyter-videochat
  - nb_conda_kernels
  - nbformat
  - nbgitpuller
  - nodejs
  - notebook
  - package_has_been_revoked # without this we get build error:- nothing provides package_has_been_revoked needed by gxx_linux-64-7.2.0-24
  - pip
  - pyflakes
  - pygithub
  - python>=3.8
  - python-lsp-server[all]
  - pyyaml
  - rclone
  - requests
  - tinydb
  - tornado
  - widgetsnbextension
  - yarn
  - pip:
      - /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl
      - pre-commit
      - ggshield