name: venv
channels:
  - conda-forge
dependencies:
  - r-purrr
  - r-optparse
  - r-nloptr
  - r-colorspace
  - r-farver
  - r-labeling
  - r-munsell
  - r-rcolorbrewer
  - r-viridislite
  - r-nloptr
  - r-gtable
  - r-isoband
  - r-scales
  - r-generics
  - r-timechange
  - r-minqa
  - r-insight
  - r-plyr
  - r-ggplot2
  - r-gridextra
  - r-evd
  - r-lubridate
  - r-lme4
  - r-reshape2
  - r-reshape
  - r-mumin
  - r-numderiv
  - r-rcpproll
  - r-mumin
  - r-jsonlite
  - r-pacman
  - r-dplyr
  - r-stringr
  - r-httr
  - r-readr
  - r-here
  - r-lubridate
  - r-tidyr
  - r-taxize
  - r-geosphere
  - r-memoise
  - r-sass
  - r-checkmate
  - r-htmlwidgets
  - r-bslib
  - r-tinytex
  - r-highr
  - r-reprex
  - r-htmltable
  - r-rmarkdown
  - r-knitr
  - r-formula
  - r-triebeard
  - r-wikipedir
  - r-wikidataqueryservicer
  - r-hmisc
  - r-pbapply
  - r-urltools
  - r-httpcode
  - r-iterators
  - r-rentrez
  - r-rncl
  - r-solrium
  - r-wikidatar
  - r-fastmatch
  - r-igraph
  - r-quadprog
  - r-foreach
  - r-zoo
  - r-data.table
  - r-bold
  - r-rredlist
  - r-ritis
  - r-worrms
  - r-natserv
  - r-wikitaxa
  - r-phangorn
  - r-conditionz
