FROM {{ base_image.build }} AS build
COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yaml .
RUN micromamba install -y -n venv -f environment.yaml
ARG MAMBA_DOCKERFILE_ACTIVATE=1
USER root
RUN conda-pack -p /opt/conda/envs/venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

{% if task_name.startswith('visualize-')%}
FROM jupyter/base-notebook AS runtime
{% else %}
FROM {{ base_image.runtime }} AS runtime
{% endif %}
COPY --from=build /venv /venv
WORKDIR /app
COPY . .