FROM qcdis/miniconda3-pdal AS build
COPY {{ task_name }}-environment.yaml .
RUN conda env update -f {{ task_name }}-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM debian:buster AS runtime
RUN apt update -y && apt upgrade -y && apt install jq
COPY --from=build /venv /venv
COPY {{ task_name }}.py .
