{% if base_image.startswith('qcdis/python-vol2bird') %}
FROM continuumio/miniconda3:22.11.1 AS build
COPY {{ task_name }}-environment.yaml .
RUN conda env update -n venv -f {{ task_name }}-environment.yaml
RUN conda install -c conda-forge conda-pack
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM {{ base_image }} AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY {{ task_name }}.py .


{% elif base_image.startswith('jupyter/r-notebook') %}
FROM {{ base_image }}

USER root

RUN R -e "install.packages('optparse', repos='http://cran.rstudio.com')"

RUN mkdir -p /app
COPY {{ task_name }}.R /app
{% else %}

FROM {{ base_image }} AS build
COPY {{ task_name }}-environment.yaml .
RUN conda env update -n venv -f {{ task_name }}-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM python:3.11-slim-bullseye AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY {{ task_name }}.py .
{% endif %}
