on:
  issues:
    types:
      - opened
  workflow_call:
    secrets: 
      personal_access_token:
        required: true

jobs:
  add-to-project:
    name: Add issue to Projects overview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/QCDIS/projects/45
          github-token: ${{ secrets.personal_access_token }}
