name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup npm
      uses: actions/setup-node@v1
      with:
          node-version: 15
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
        npm install @mrblenny/react-flow-chart@"^0.0.14" 
        npm install @types/node --save-dev
        npm install lerna
        npm install
    - name: build
      run: |
        make release
