name: build


on:
  push:
  release:
    types: [created]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
jobs:
  build:
    name: Build distributions 
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install requirements  
      run: |
        $CONDA/bin/conda install jupyterlab nodejs yarn
        $CONDA/bin/conda install -c conda-forge typescript
    - name: npm install requirements
      run: |
        npm install @mrblenny/react-flow-chart@"^0.0.14"
        npm install @types/node --save-dev
        npm install lerna
    - name: npm install
      run: |
        npm install
        
