name: Build wheel

on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          
      - name: make release
        shell: bash -el {0}
        run: make release
      - name: 'Upload wheel artifact'
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab_vre
          path: dist/jupyterlab_vre-0.1.0-py3-none-any.whl
