name: Build container

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      tag:
        required: true
        type: string
      wheel_artifact_name:
        required: true
        type: string
      push:
        required: true
        type: boolean

image_id: "registry.gitlab.com/qcd1/registry/n-a-a-vre"

env:
  DOCKERFILE:  ${{ inputs.dockerfile }}
  TAG:  ${{ inputs.tag }}
  GITLAB_IMAGE_ID: "registry.gitlab.com/qcd1/registry/"
  DOCKERHUB_IMAGE_ID: "qcdis/"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.wheel_artifact_name }}

    - name: Build docker
      run: |
          mv jupyterlab_vre-0.1.0-py3-none-any.whl docker/
          cd docker && docker build . --file $DOCKERFILE -t $TAG

    - name: Start docker
      run: |
          docker run -d -p 8888:8888 -host=172.17.0.2 $TAG:latest jupyter lab

    - name: Login to gitlab Registry
      uses: docker/login-action@v1
      with:
        registry: "registry.gitlab.com/qcd1/registry"
        username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
        password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
    - name: Push image to container Registry
      run: |
        # Change all uppercase to lowercase
        IMAGE_ID=$GITLAB_IMAGE_ID$TAG
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $TAG $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        docker tag $TAG $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
      if: ${{ inputs.push }}

    - name: Login to github Registry
      uses: docker/login-action@v1
      with:
        registry: "https://index.docker.io/v1/"
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to container Registry
      run: |
        # Change all uppercase to lowercase
        IMAGE_ID=$DOCKERHUB_IMAGE_ID$TAG
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $TAG $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        docker tag $TAG $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
      if: ${{ inputs.push }}
