name: Build wheel

on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
          python setup.py install

      - name: setup env
        run: |
           python docker/repo_utils/conf_vl_repos.py --force=True --github_url=${{ secrets.CELL_GITHUB }} --github_token=${{ secrets.CELL_GITHUB_TOKEN }} --registry_url=${{ secrets.REGISTRY_URL }}

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest  --ignore=docker

      - name: make release
        shell: bash -el {0}
        run: make release
      - name: 'Upload wheel artifact'
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab_vre
          path: dist/jupyterlab_vre-0.1.0-py3-none-any.whl
