name: build


on:
  push:
  release:
    types: [created]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
jobs:
  build:
    name: Build distributions 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build wheel
        run: |
          pip install jupyterlab && cd packages/core && jupyter labextension install --no-build . && jupyter labextension link --no-build .make release && cd ../ && make release
