name: build


on:
  push:
  release:
    types: [created]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
jobs:
  build-and-publish:
    name: Build distributions 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel jupyterhub
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Build a binary wheel and a source tarball
        run: |
          make release
