name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
        npm install @mrblenny/react-flow-chart@"^0.0.14" 
        npm install @types/node --save-dev
        npm install lerna
        npm install
        npx lerna run build --scope @jupyter_vre/core --loglevel debug
