name: Build wheel

on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup npm
      uses: actions/setup-node@v1
      with:
          node-version: 16
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
        $CONDA/bin/conda install jupyterlab nodejs yarn
        $CONDA/bin/conda install -c conda-forge typescript
    - name: Install nodejs dependencies
      run: |
        npm install lerna --force
        npm install --force
    - name: make
      run: |
        npx lerna run build --scope @jupyter_vre/core
        npx lerna run build --scope @jupyter_vre/chart-customs
        npx lerna run build --scope @jupyter_vre/components
        npx lerna run build --scope @jupyter_vre/core
        make install-backend && make build-frontend && make install-ui && make link-ui
        make release
    - name: 'Upload wheel artifact'
      uses: actions/upload-artifact@v3
      with:
        name: jupyterlab_vre
        path: dist/jupyterlab_vre-0.1.0-py3-none-any.whl
      if: ${{ inputs.upload }}
