name: Build wheel and test Docker

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup npm
      uses: actions/setup-node@v1
      with:
          node-version: 17
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
        npm install @mrblenny/react-flow-chart@"^0.0.14" 
        npm install @types/node@"^12.13.0 || ^14.15.0 || >=16" --save-dev
        npm install lerna
        npm install
    - name: build
      run: |
          npx lerna run build --scope @jupyter_vre/core
          npx lerna run build
          make release
    - name: Build docker
      run: |
          cp dist/jupyterlab_vre-0.1.0-py3-none-any.whl docker/
          cd docker && docker build . --file Dockerfile -t n-a-a-vre
    - name: Start docker
      run: |
          docker run -d -p 8888:8888 -host=172.17.0.2 n-a-a-vre:latest jupyter lab
          sleep 5
#     - name: Run API Tests
#       id: run-newman
#       uses: anthonyvscode/newman-action@v1
#       with:
#         collection: postman/postman_collection.json
#         environment: postman/postman_environment.json
#         reporters: cli
#         iterationCount: 3
          
#     - uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         commit_message:  new whl file
#         file_pattern: docker/*.whl
#         skip_fetch: true
#         skip_checkout: true
    - name: Save whl
      uses: actions/upload-artifact@v2
      with:
        name: save
        path: |
          docker/jupyterlab_vre-0.1.0-py3-none-any.whl
          
          
