name: Build wheel and test Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup npm
      uses: actions/setup-node@v1
      with:
          node-version: 17
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
        npm install @mrblenny/react-flow-chart@"^0.0.14" 
        npm install @types/node@"^12.13.0 || ^14.15.0 || >=16" --save-dev
        npm install lerna
        npm install
    - name: build
      run: |
          npx lerna run build --scope @jupyter_vre/core
          npx lerna run build
          make release
    - name: Build docker
      run: |
          cp dist/jupyterlab_vre-0.1.0-py3-none-any.whl docker/
          cd docker && docker build . --file Dockerfile
          
