name: Build docker

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
          cp dist/jupyterlab_vre-0.1.0-py3-none-any.whl docker/
          cd docker && docker build . --file Dockerfile -t n-a-a-vre
    - name: Start docker
      run: |
          docker run -d -p 8888:8888 -host=172.17.0.2 n-a-a-vre:latest jupyter lab