name: Build container

on:
  workflow_call:
    inputs:
      wheel_artifact_name:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifcat
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.wheel_artifact_name }}

    - name: Build docker
      run: |
          mv jupyterlab_vre-0.1.0-py3-none-any.whl docker/
          cd docker && docker build . --file Dockerfile -t n-a-a-vre
    - name: Start docker
      run: |
          docker run -d -p 8888:8888 -host=172.17.0.2 n-a-a-vre:latest jupyter lab

    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "n-a-a-vre:latest"
