name: Build docker
on: [push]

#on:
#  push:
#  release:
#    types: [created]
#    # Publish `v1.2.3` tags as releases.
#    tags:
#      - v*

env:
  IMAGE_NAME:  n-a-a-vre
  GITLAB: registry.gitlab.com/qcd1/registry
  GITHUB: qcdis

jobs:
  call-build-wheel:
    uses: build-wheel.yml@main