name: Build wheel

on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: etc/example-environment.yml
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v4
#      with:
#        python-version: 3.9
#    - name: Setup npm
#      uses: actions/setup-node@v3
#      with:
#          node-version: 16
#    - name: Install conda env
#      run: |
#        $CONDA/bin/conda env update --file environment.yml --name base
#    - name: make
#      run: |
#        make release
#    - name: 'Upload wheel artifact'
#      uses: actions/upload-artifact@v3
#      with:
#        name: jupyterlab_vre
#        path: dist/jupyterlab_vre-0.1.0-py3-none-any.whl
#      if: ${{ inputs.upload }}
