name: Docker
on: [push]

#on:
#  push:
#  release:
#    types: [created]
#    # Publish `v1.2.3` tags as releases.
#    tags:
#      - v*

env:
  IMAGE_NAME:  n-a-a-vre
  GITLAB: registry.gitlab.com/qcd1/registry
  GITHUB: qcdis

jobs:
  call-build-wheel:
    uses: ./.github/workflows/build-wheel.yml
  build-container:
    needs: call-build-wheel
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
#  build-docker:
#    needs: build-container
#    uses: ./.github/workflows/registry-push.yml
#    with:
#      registry: $GITLAB
#      image_id: $GITLAB/$IMAGE_NAME
