name: Docker
on: [push]

#on:
#  push:
#  release:
#    types: [created]
#    # Publish `v1.2.3` tags as releases.
#    tags:
#      - v*



jobs:
#  call-build-wheel:
#    uses: ./.github/workflows/build-wheel.yml
#  call-build-container:
#    needs: call-build-wheel
#    uses: ./.github/workflows/build-container.yml
#    with:
#      wheel_artifact_name: jupyterlab_vre
  call-registry-push:
#    needs: call-build-container
    uses: ./.github/workflows/registry-push.yml
    with:
      registry: "registry.gitlab.com/qcd1/registry"
      image_id: "registry.gitlab.com/qcd1/registry/n-a-a-vre"
    secrets:
      registry_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

