name: make
on:
  release:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  configure-workflow:
    name: Configure workflow
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      runner: ${{ steps.choose-runner.outputs.runner }}
    steps:
      - id: skip_check
        name: Configure skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md"]'  # FIXME
          do_not_skip: '["workflow_dispatch", "schedule", "release"]'
      - id: choose-runner
        uses: QCDIS/choose-action-runner@v2
        with:
          preferred-runner: naavre
          fallback-runner: ubuntu-latest
          github-token: ${{ secrets.RUNNER_ACCESS_TOKEN }}

  call-pytest:
    uses: ./.github/workflows/test-build wheel.yml
    needs: [configure-workflow]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' }}
    with:
      runs-on: ${{ needs.configure-workflow.outputs.runner }}
    secrets:
      jupyterhub_user: ${{ secrets.JUPYTERHUB_USER }}
      vlab_slug: ${{ secrets.VLAB_SLUG }}
      cell_github: ${{ secrets.CELL_GITHUB }}
      cell_github_token:  ${{ secrets.CELL_GITHUB_TOKEN }}
      api_endpoint: ${{ secrets.API_ENDPOINT }}
      module_mapping_url: ${{ secrets.MODULE_MAPPING_URL }}
      search_api_endpoint: ${{ secrets.SEARCH_API_ENDPOINT }}
      search_api_token: ${{ secrets.SEARCH_API_TOKEN }}
      registry_url: ${{ secrets.REGISTRY_URL }}
      naavre_api_token: ${{ secrets.NAAVRE_API_TOKEN }}
      argo_url: ${{ secrets.ARGO_URL }}
      argo_api_token: ${{ secrets.ARGO_API_TOKEN }}

  call-build-container-vanilla:
    needs: [call-pytest]
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: vanilla
      tag: n-a-a-vre
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
