name: make
on:
  [pull_request,push]
jobs:
  call-build-wheel:
    uses: QCDIS/NaaVRE/.github/workflows/build-wheel.yml@main
    with:
      upload: true
  call-build-container-laserfarm:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: n-a-a-vre-laserfarm
      push: false
  call-build-container-multiply:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-MULTIPLY
      tag: n-a-a-vre-multiply
      push: false
  call-build-container-vol2bird:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-vol2bird
      tag: n-a-a-vre-vol2bird
      push: false
  call-build-container-pytorch:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: n-a-a-vre-pytorch
      push: false