name: make
on:
  pull_request_target:
  push:
    tags:
    - '*'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  call-pytest:
    uses: QCDIS/NaaVRE/.github/workflows/python-package-conda.yml@896-conda-environment-on-test-runners
    secrets:
      jupyterhub_user: ${{ secrets.JUPYTERHUB_USER }}
      vlab_slug: ${{ secrets.VLAB_SLUG }}
      cell_github: ${{ secrets.CELL_GITHUB }}
      cell_github_token:  ${{ secrets.CELL_GITHUB_TOKEN }}
      api_endpoint: ${{ secrets.API_ENDPOINT }}
      module_mapping_url: ${{ secrets.MODULE_MAPPING_URL }}
      search_api_endpoint: ${{ secrets.SEARCH_API_ENDPOINT }}
      search_api_token: ${{ secrets.SEARCH_API_TOKEN }}
      registry_url: ${{ secrets.REGISTRY_URL }}
      naavre_api_token: ${{ secrets.NAAVRE_API_TOKEN }}
      argo_url: ${{ secrets.ARGO_URL }}
      argo_api_token: ${{ secrets.ARGO_API_TOKEN }}
  call-build-wheel:
    needs: call-pytest
    uses: QCDIS/NaaVRE/.github/workflows/build-wheel.yml@896-conda-environment-on-test-runners
    with:
      upload: true
  call-build-container-laserfarm:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@896-conda-environment-on-test-runners
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: laserfarm-pytorch
      tag: n-a-a-vre-laserfarm
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vol2bird:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@896-conda-environment-on-test-runners
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: vol2bird
      tag: n-a-a-vre-vol2bird
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vanilla:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@896-conda-environment-on-test-runners
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: vanilla
      tag: n-a-a-vre
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
