name: make release
on:
  push:
    tags:
      - '*'

jobs:
  cleanup-artifacts:
    uses: QCDIS/NaaVRE/.github/workflows/artifacts-cleanup.yaml@main
  call-build-wheel:
    needs: cleanup-artifacts
    uses: QCDIS/NaaVRE/.github/workflows/build-wheel.yml@main
    with:
      upload: true
  call-save-in-relese:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/save-wheel-in-release.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
  call-build-container-laserfarm:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: n-a-a-vre-laserfarm
      push: true
  call-build-container-multiply:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-MULTIPLY
      tag: n-a-a-vre-multiply
      push: true
  call-build-container-vol2bird:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-vol2bird
      tag: n-a-a-vre-vol2bird
      push: true
  call-build-container-pytorch:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: n-a-a-vre-pytorch
      push: true