name: make relese
on:
  push:
  release:
    types: [created]
    tags:
      - v*



jobs:
  call-build-wheel:
    uses: ./.github/workflows/build-wheel.yml
  call-build-container:
    needs: call-build-wheel
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
  call-registry-push-gitlab:
    needs: call-build-container
    uses: ./.github/workflows/registry-push.yml
    with:
      registry: "registry.gitlab.com/qcd1/registry"
      image_id: "registry.gitlab.com/qcd1/registry/n-a-a-vre"
    secrets:
      registry_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

  call-registry-push-dockerhub:
    needs: call-build-container
    uses: ./.github/workflows/registry-push.yml
    with:
      registry: "https://index.docker.io/v1/"
      image_id: "qcdis/n-a-a-vre"
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}

