name: make
on:
  release:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  choose-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.choose-runner.outputs.runner }}
    steps:
      - id: choose-runner
        uses: QCDIS/chose-action-runner@v1
        with:
          preferred-runner: naavre
          fallback-runner: ubuntu-latest
          github-token: ${{ secrets.RUNNER_ACCESS_TOKEN }}

  call-pytest:
    needs: [choose-runner]
    uses: ./.github/workflows/test-build wheel.yml
    with:
      runs-on: ${{ needs.choose-runner.outputs.runner }}
    secrets:
      jupyterhub_user: ${{ secrets.JUPYTERHUB_USER }}
      vlab_slug: ${{ secrets.VLAB_SLUG }}
      cell_github: ${{ secrets.CELL_GITHUB }}
      cell_github_token:  ${{ secrets.CELL_GITHUB_TOKEN }}
      api_endpoint: ${{ secrets.API_ENDPOINT }}
      module_mapping_url: ${{ secrets.MODULE_MAPPING_URL }}
      search_api_endpoint: ${{ secrets.SEARCH_API_ENDPOINT }}
      search_api_token: ${{ secrets.SEARCH_API_TOKEN }}
      registry_url: ${{ secrets.REGISTRY_URL }}
      naavre_api_token: ${{ secrets.NAAVRE_API_TOKEN }}
      argo_url: ${{ secrets.ARGO_URL }}
      argo_api_token: ${{ secrets.ARGO_API_TOKEN }}
  call-build-container-laserfarm:
    needs: [call-pytest]
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: laserfarm-pytorch
      tag: n-a-a-vre-laserfarm
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vol2bird:
    needs: [call-pytest]
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: vol2bird
      tag: n-a-a-vre-vol2bird
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vanilla:
    needs: [call-pytest]
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: vanilla
      tag: n-a-a-vre
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-lter-life:
    needs: [call-pytest]
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: lter-life
      tag: n-a-a-vre-lter-life
      push: ${{ github.event_name == 'release' }}
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
