name: make release
on:
  push:
    tags:
      - '*'

jobs:
  call-build-wheel:
    uses: ./.repository/workflows/build-wheel.yml@main
  call-save-in-relese:
    needs: call-build-wheel
    uses: ./.repository/workflows/save-wheel-in-release.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
  call-build-container:
    needs: call-build-wheel
    uses: ./.repository/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile
      tag: n-a-a-vre
  call-build-container-laserfarm:
    needs: call-build-wheel
    uses: ./.repository/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm
      tag: n-a-a-vre-laserfarm
  call-registry-push-gitlab:
    needs: call-build-container
    uses: ./.repository/workflows/registry-push.yml@main
    with:
      registry: "registry.gitlab.com/qcd1/registry"
      image_id: "registry.gitlab.com/qcd1/registry/n-a-a-vre"
      tag: n-a-a-vre
    secrets:
      registry_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
  call-registry-push-gitlab-laserfarm:
    needs: call-build-container-laserfarm
    uses: ./.repository/workflows/registry-push.yml@main
    with:
      registry: "registry.gitlab.com/qcd1/registry"
      image_id: "registry.gitlab.com/qcd1/registry/n-a-a-vre-laserfarm"
      tag: n-a-a-vre-laserfarm
    secrets:
      registry_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
  call-registry-push-dockerhub-laserfarm:
    needs: call-build-container-laserfarm
    uses: ./.repository/workflows/registry-push.yml@main
    with:
      registry: "https://index.docker.io/v1/"
      image_id: "qcdis/n-a-a-vre-laserfarm"
      tag: n-a-a-vre-laserfarm
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-registry-push-dockerhub:
    needs: call-build-container
    uses: ./.repository/workflows/registry-push.yml@main
    with:
      registry: "https://index.docker.io/v1/"
      image_id: "qcdis/n-a-a-vre"
      tag: n-a-a-vre
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}


