name: make relese
on:
  [pull_request]

jobs:
  call-build-wheel:
    uses: ./.github/workflows/build-wheel.yml
  call-build-container:
    needs: call-build-wheel
    uses: ./.github/workflows/build-container.yml
    with:
      wheel_artifact_name: jupyterlab_vre
