name: make
on:
  pull_request:
  push:
  schedule:
    - cron: '0 4 5,25 * *'



jobs:
#   call-pytest:
#     strategy:
#       matrix:
#         environment_names: [ "test-vars" ]
#
#     uses: QCDIS/NaaVRE/.github/workflows/python-package-conda.yml@main
#     with:
#       jupyterhub_user: ${{ vars.JUPYTERHUB_USER }}
#       environment_name:  ${{ matrix.environment_names }}
#       vlab_slug: ${{ vars.VLAB_SLUG }}
#     secrets:
#       cell_github: ${{ secrets.CELL_GITHUB }}
#       cell_github_token:  ${{ secrets.CELL_GITHUB_TOKEN }}
#       api_endpoint: ${{ secrets.API_ENDPOINT }}
#       module_mapping_url: ${{ secrets.MODULE_MAPPING_URL }}
#       search_api_endpoint: ${{ secrets.SEARCH_API_ENDPOINT }}
#       search_api_token: ${{ secrets.SEARCH_API_TOKEN }}
#       registry_url: ${{ secrets.REGISTRY_URL }}


  call-build-wheel:
#     needs: call-pytest
    uses: QCDIS/NaaVRE/.github/workflows/build-wheel.yml@main
    with:
      upload: true
  call-build-container-laserfarm:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: laserfarm-pytorch
      tag: n-a-a-vre-laserfarm
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-multiply:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: MULTIPLY
      tag: n-a-a-vre-multiply
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vol2bird:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: vol2bird
      tag: n-a-a-vre-vol2bird
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-pytorch:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: laserfarm-pytorch
      tag: n-a-a-vre-pytorch
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vanilla:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      docker_folder: vanilla
      tag: n-a-a-vre
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}