name: make
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 4 * *'

jobs:
  call-pytest:
    uses: QCDIS/NaaVRE/.github/workflows/python-package-conda.yml@main
  call-build-wheel:
    needs: call-pytest
    uses: QCDIS/NaaVRE/.github/workflows/build-wheel.yml@main
    with:
      upload: true
  call-build-container-laserfarm:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: n-a-a-vre-laserfarm
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-multiply:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-MULTIPLY
      tag: n-a-a-vre-multiply
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-vol2bird:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-vol2bird
      tag: n-a-a-vre-vol2bird
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  call-build-container-pytorch:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-container.yml@main
    with:
      wheel_artifact_name: jupyterlab_vre
      dockerfile: Dockerfile-laserfarm-pytorch
      tag: n-a-a-vre-pytorch
      push: false
    secrets:
      gitlab_username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
      gitlab_password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}