name: make
env:
  upload_wheel: false
on:
  [pull_request]
jobs:
  cleanup-artifacts:
    uses: QCDIS/NaaVRE/.github/workflows/artifacts-cleanup.yaml@main
  call-build-wheel:
    uses: QCDIS/NaaVRE/.github/workflows/build-wheel.yml@main
    needs: cleanup-artifacts
    with:
      upload: false
  call-build-containers:
    needs: call-build-wheel
    uses: QCDIS/NaaVRE/.github/workflows/build-containers.yml@main
    with:
      upload: false