name: registry push

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_id:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

env:
  IMAGE_ID:  ${{ inputs.image_id }}
  TAG:  ${{ inputs.tag }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: ${{ inputs.tag }}

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    - name: Push image to container Registry
      run: |
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $TAG $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION