name: registry push

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_id:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Gitlab Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}