name: registry push

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_id:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

env:
  IMAGE_ID:  ${{ inputs.image_id }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "n-a-a-vre:latest"

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}
    - name: Push image to container Registry
      run: |
        echo "$IMAGE_ID"