name: registry push

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_id:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Login to Gitlab Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
        password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}