name: save wheel file

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      wheel_artifact_name:
        required: true
        type: string


jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Download artifcat
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.wheel_artifact_name }}

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'jupyterlab_vre-0.1.0-py3-none-any.whl'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
