name: Build wheel

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      api_endpoint:
        required: true
        type: string
      cell_github:
        required: true
        type: string
      debug:
        required: true
        type: string
      group:
        required: true
        type: string
      jupyterhub_user:
        required: true
        type: string
      module_mapping_url:
        required: true
        type: string
      registry_url:
        required: true
        type: string
      search_api_endpoint:
        required: true
        type: string
      vlab_slug:
        required: true
        type: string
    secrets:
      cell_github_token:
        required: true
      naavre_api_token:
        required: true
      search_api_token:
        required: true

env:
  CELL_GITHUB: ${{ inputs.cell_github }}
  CELL_GITHUB_TOKEN: ${{ secrets.cell_github_token }}
  REGISTRY_URL: ${{ inputs.registry_url }}
  NAAVRE_API_TOKEN: ${{ secrets.naavre_api_token }}
  JUPYTERHUB_USER: ${{ inputs.jupyterhub_user }}
  API_ENDPOINT: ${{ inputs.api_endpoint }}
  VLAB_SLUG: ${{ inputs.vlab_slug }}
  MODULE_MAPPING_URL: ${{ inputs.module_mapping_url }}
  SEARCH_API_ENDPOINT: ${{ inputs.search_api_endpoint }}
  SEARCH_API_TOKEN: ${{ secrets.search_api_token }}
  ASYNC_TEST_TIMEOUT: 30
  DEBUG: ${{ inputs.debug }}


jobs:
  build-wheel:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          python-version: 3.11
          path: ${{ env.CONDA }}/envs
          environment-file: environment.yml
          activate-environment: jupyterlab
          use-mamba: true

      - name: print group
        shell: bash -l {0}
        run: |
          echo ${{ inputs.group }}

      - name: Cache Conda environment
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-environment-${{ runner.os }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            conda-environment-${{ runner.os }}-
        id: cache-conda

#      - name: Update environment
#        if: steps.cache-conda.outputs.cache-hit != 'true'
#        run:
#          mamba env update -n jupyterlab -f environment.yml

      - name: pytest
        shell: bash -l {0}
        run: |
          conda activate jupyterlab
          conda install -y conda-forge::pytest-cov
          conda install -y conda-forge::pytest-split
          python docker/repo_utils/conf_vl_repos.py  --force=True
          pip install --upgrade build
          mkdir -p /tmp/data
          pytest  -s --ignore=docker --ignore=cypress --no-header -v --cov --splits 3 --group ${{ inputs.group }}

      - name: make release
        shell: bash -el {0}
        run: make release

      - name: 'Upload wheel artifact'
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab_vre
          path: dist/jupyterlab_vre-0.1.0-py3-none-any.whl

      - name: Print conda environment
        shell: bash -el {0}
        run: conda env export

      - name: Print conda yarn.lock
        shell: bash -el {0}
        run: cat yarn.lock
